# Generated by Django 2.1.5 on 2019-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_price', models.IntegerField(blank=True, null=True, verbose_name='Asset Price')),
                ('other_cost', models.IntegerField(blank=True, null=True, verbose_name='All other Costs')),
                ('ltv', models.FloatField(blank=True, null=True, verbose_name='Bank Contribution')),
                ('roi', models.FloatField(blank=True, null=True, verbose_name='Rate of Interest')),
                ('tenure', models.IntegerField(blank=True, null=True, verbose_name='Tenure')),
                ('annual_early_repay', models.IntegerField(blank=True, null=True, verbose_name='Annual Early Repay')),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='Date of Purchase')),
                ('months_to_possession', models.IntegerField(blank=True, null=True, verbose_name='Months to possess')),
                ('monthly_rent_earning', models.IntegerField(blank=True, null=True, verbose_name='Monthly Rent')),
                ('annual_maintenance', models.IntegerField(blank=True, null=True, verbose_name='Annual Maintenance')),
                ('annual_prop_tax', models.IntegerField(blank=True, null=True, verbose_name='Property Tax')),
                ('limit_80c', models.IntegerField(blank=True, null=True, verbose_name='80c Limit')),
                ('self_pf_contri', models.IntegerField(blank=True, null=True, verbose_name='Self Contribution of PF')),
                ('int_rebate_limit', models.IntegerField(blank=True, null=True, verbose_name='LOH Rebate')),
                ('rd_rate', models.FloatField(blank=True, null=True, verbose_name='FD interest rate')),
            ],
        ),
    ]
